"""
Phase 8: Canonical Knowledge Graph, Timeline, and Story Seed Engine
Populates Turso Cloud with verified, evidence-grounded entities, aliases,
provenance-backed relationships, precision-aware timeline events, and curated stories.
Every single relationship and event is strictly anchored to verified document chunks.
"""
from __future__ import annotations

import json
import logging
import uuid
from app.db.database import DatabaseClient

logger = logging.getLogger("ambedkar.kg.seed")

# ── Seed Entities ─────────────────────────────────────────────────────────────
CANONICAL_ENTITIES = [
    {
        "id": "person-ambedkar",
        "entity_type": "PERSON",
        "canonical_name": "Dr. B.R. Ambedkar",
        "description": "Chief Architect of the Constitution of India, jurist, economist, scholar, and social revolutionary.",
        "date": "1891-04-14",
        "date_precision": "DAY",
        "location": "Mhow, Central Provinces",
        "aliases": ["B. R. Ambedkar", "B R Ambedkar", "Dr. B. R. Ambedkar", "Dr Bhimrao Ramji Ambedkar", "Babasaheb", "Babasaheb Ambedkar"],
        "external_identifiers": {"wikidata": "Q2339", "viaf": "2609992"},
        "object_id": "AMBEDKAR-VOL-01",
    },
    {
        "id": "person-gandhi",
        "entity_type": "PERSON",
        "canonical_name": "Mahatma Gandhi",
        "description": "Leader of the Indian nationalist movement, signatory to the Poona Pact of 1932 with Dr. Ambedkar.",
        "date": "1869-10-02",
        "date_precision": "DAY",
        "location": "Porbandar, Gujarat",
        "aliases": ["M. K. Gandhi", "Mohandas Karamchand Gandhi", "Mahatma Gandhi", "Mr. Gandhi"],
        "external_identifiers": {"wikidata": "Q1001"},
        "object_id": "AMBEDKAR-VOL-01",
    },
    {
        "id": "person-dewey",
        "entity_type": "PERSON",
        "canonical_name": "Prof. John Dewey",
        "description": "American philosopher and educator at Columbia University whose pragmatism shaped Dr. Ambedkar's democratic theory.",
        "date": "1859-10-20",
        "date_precision": "DAY",
        "location": "Burlington, Vermont",
        "aliases": ["John Dewey", "Prof. Dewey", "Professor John Dewey"],
        "external_identifiers": {"wikidata": "Q132543"},
        "object_id": "AMBEDKAR-VOL-01",
    },
    {
        "id": "person-nehru",
        "entity_type": "PERSON",
        "canonical_name": "Jawaharlal Nehru",
        "description": "First Prime Minister of India, who invited Dr. Ambedkar to serve as India's first Law Minister.",
        "date": "1889-11-14",
        "date_precision": "DAY",
        "location": "Allahabad, United Provinces",
        "aliases": ["Pandit Nehru", "J. L. Nehru", "Jawaharlal Nehru"],
        "external_identifiers": {"wikidata": "Q1047"},
        "object_id": "AMBEDKAR-VOL-13",
    },
    {
        "id": "work-annihilation",
        "entity_type": "WORK",
        "canonical_name": "Annihilation of Caste",
        "description": "1936 undelivered presidential address written for the Jat-Pat-Todak Mandal of Lahore, analyzing caste endogamy and shastric authority.",
        "date": "1936",
        "date_precision": "YEAR",
        "location": "Lahore / Bombay",
        "aliases": ["Annihilation of Caste", "AoC", "Undelivered Speech 1936"],
        "object_id": "AMBEDKAR-VOL-01",
    },
    {
        "id": "work-castes-in-india",
        "entity_type": "WORK",
        "canonical_name": "Castes in India: Their Mechanism, Genesis and Development",
        "description": "1916 paper presented at the Columbia University Anthropology Seminar under Alexander Goldenweiser, establishing endogamy as caste mechanism.",
        "date": "1916-05-09",
        "date_precision": "DAY",
        "location": "Columbia University, New York",
        "aliases": ["Castes in India", "Castes in India Paper"],
        "object_id": "AMBEDKAR-VOL-01",
    },
    {
        "id": "work-problem-of-rupee",
        "entity_type": "WORK",
        "canonical_name": "The Problem of the Rupee: Its Origin and Its Solution",
        "description": "1923 doctoral dissertation at the London School of Economics examining British colonial currency policy and exchange standards.",
        "date": "1923",
        "date_precision": "YEAR",
        "location": "London School of Economics",
        "aliases": ["Problem of the Rupee", "The Problem of the Rupee"],
        "object_id": "AMBEDKAR-VOL-06",
    },
    {
        "id": "work-states-minorities",
        "entity_type": "WORK",
        "canonical_name": "States and Minorities",
        "description": "1947 memorandum submitted to the Constituent Assembly proposing a constitutional framework for State Socialism and minority protection.",
        "date": "1947",
        "date_precision": "YEAR",
        "location": "New Delhi",
        "aliases": ["States and Minorities", "States & Minorities"],
        "object_id": "AMBEDKAR-VOL-01",
    },
    {
        "id": "work-riddles-in-hinduism",
        "entity_type": "WORK",
        "canonical_name": "Riddles in Hinduism",
        "description": "Philosophical and historical critique investigating contradictions in traditional brahmanical scriptures and epics.",
        "date": "1954",
        "date_precision": "APPROXIMATE",
        "location": "Bombay",
        "aliases": ["Riddles in Hinduism", "Riddles in Hinduism Monograph"],
        "object_id": "AMBEDKAR-VOL-04",
    },
    {
        "id": "work-buddha-and-dhamma",
        "entity_type": "WORK",
        "canonical_name": "The Buddha and His Dhamma",
        "description": "Magnum opus rationalist reinterpretation of Buddhism emphasizing ethical morality (Dhamma) over religious ritualism.",
        "date": "1957",
        "date_precision": "YEAR",
        "location": "Bombay / Nagpur",
        "aliases": ["The Buddha and His Dhamma", "Buddha and His Dhamma"],
        "object_id": "AMBEDKAR-VOL-11",
    },
    {
        "id": "org-columbia",
        "entity_type": "ORGANIZATION",
        "canonical_name": "Columbia University",
        "description": "New York university where Dr. Ambedkar studied economics, politics, sociology, and philosophy (1913-1916).",
        "date": "1754",
        "date_precision": "YEAR",
        "location": "New York City, USA",
        "aliases": ["Columbia", "Columbia University in the City of New York"],
        "object_id": "AMBEDKAR-VOL-01",
    },
    {
        "id": "org-lse",
        "entity_type": "ORGANIZATION",
        "canonical_name": "London School of Economics",
        "description": "Premier British institution where Dr. Ambedkar completed his M.Sc. and D.Sc. in Economics.",
        "date": "1895",
        "date_precision": "YEAR",
        "location": "London, UK",
        "aliases": ["LSE", "London School of Economics and Political Science"],
        "object_id": "AMBEDKAR-VOL-06",
    },
    {
        "id": "org-drafting-committee",
        "entity_type": "ORGANIZATION",
        "canonical_name": "Drafting Committee of the Constituent Assembly",
        "description": "Constitutional committee established on 29 August 1947, chaired by Dr. B.R. Ambedkar to draft the Constitution of India.",
        "date": "1947-08-29",
        "date_precision": "DAY",
        "location": "Constitution Hall, New Delhi",
        "aliases": ["Drafting Committee", "Constitution Drafting Committee"],
        "object_id": "AMBEDKAR-VOL-13",
    },
    {
        "id": "org-rbi",
        "entity_type": "ORGANIZATION",
        "canonical_name": "Reserve Bank of India",
        "description": "Central banking institution formed in 1935 following the Hilton-Young Commission, conceptually founded on Ambedkar's currency treatise.",
        "date": "1935-04-01",
        "date_precision": "DAY",
        "location": "Calcutta / Bombay",
        "aliases": ["RBI", "Reserve Bank of India", "Reserve Bank"],
        "object_id": "AMBEDKAR-VOL-01",
    },
    {
        "id": "org-bahishkrit-sabha",
        "entity_type": "ORGANIZATION",
        "canonical_name": "Bahishkrit Hitakarini Sabha",
        "description": "Socio-political organization founded by Dr. Ambedkar on 20 July 1924 with the motto: 'Educate, Agitate, Organise'.",
        "date": "1924-07-20",
        "date_precision": "DAY",
        "location": "Damodar Hall, Parel, Bombay",
        "aliases": ["Bahishkrit Hitakarini Sabha", "Depressed Classes Institute"],
        "object_id": "AMBEDKAR-VOL-17-P1",
    },
    {
        "id": "event-mahad",
        "entity_type": "EVENT",
        "canonical_name": "Mahad Satyagraha",
        "description": "Historic civil rights movement asserting public access to water at Chhadar Tank in Mahad, Maharashtra.",
        "date": "1927-03-20",
        "date_precision": "DAY",
        "location": "Mahad, Kolaba District",
        "aliases": ["Mahad Satyagraha", "Chhadar Tank Satyagraha", "Mahad Water Satyagraha"],
        "object_id": "AMBEDKAR-VOL-17-P1",
    },
    {
        "id": "event-manusmriti-dahan",
        "entity_type": "EVENT",
        "canonical_name": "Manusmriti Dahan Din",
        "description": "Public ceremonial burning of the Manusmriti code in Mahad on 25 December 1927 as a declaration of universal human equality.",
        "date": "1927-12-25",
        "date_precision": "DAY",
        "location": "Mahad, Kolaba District",
        "aliases": ["Manusmriti Burning", "Manusmriti Dahan"],
        "object_id": "AMBEDKAR-VOL-17-P1",
    },
    {
        "id": "event-poona-pact",
        "entity_type": "EVENT",
        "canonical_name": "Poona Pact",
        "description": "Agreement negotiated between Dr. Ambedkar and caste Hindu leaders at Yerwada Central Jail securing reserved seats for Depressed Classes.",
        "date": "1932-09-24",
        "date_precision": "DAY",
        "location": "Yerwada Central Jail, Poona",
        "aliases": ["Poona Pact", "Yerwada Agreement 1932"],
        "object_id": "AMBEDKAR-VOL-01",
    },
    {
        "id": "event-round-table",
        "entity_type": "EVENT",
        "canonical_name": "Round Table Conferences",
        "description": "Three peace conferences organized by the British Government in London to discuss constitutional reforms for India.",
        "date": "1930",
        "date_precision": "RANGE",
        "location": "St. James's Palace, London",
        "aliases": ["Round Table Conference", "RTC London"],
        "object_id": "AMBEDKAR-VOL-01",
    },
    {
        "id": "event-conversion-1956",
        "entity_type": "EVENT",
        "canonical_name": "Nagpur Buddhist Conversion",
        "description": "Mass conversion ceremony at Deekshabhoomi, Nagpur on 14 October 1956 where Dr. Ambedkar and 500,000 followers embraced Buddhism.",
        "date": "1956-10-14",
        "date_precision": "DAY",
        "location": "Deekshabhoomi, Nagpur",
        "aliases": ["1956 Buddhist Conversion", "Nagpur Conversion", "Deekshabhoomi Dhamma Diksha"],
        "object_id": "AMBEDKAR-VOL-11",
    },
    {
        "id": "concept-social-endosmosis",
        "entity_type": "CONCEPT",
        "canonical_name": "Social Endosmosis",
        "description": "The continuous, unobstructed communication and sharing of varied interests and experiences across diverse social groups as the essence of democracy.",
        "date": "1916",
        "date_precision": "YEAR",
        "aliases": ["Endosmosis", "Social Endosmosis"],
        "object_id": "AMBEDKAR-VOL-01",
    },
    {
        "id": "concept-constitutional-morality",
        "entity_type": "CONCEPT",
        "canonical_name": "Constitutional Morality",
        "description": "Strict adherence to democratic norms, checks and balances, and institutional restraint over majoritarian populist impulses.",
        "date": "1948-11-04",
        "date_precision": "DAY",
        "aliases": ["Constitutional Morality", "Doctrine of Constitutional Morality"],
        "object_id": "AMBEDKAR-VOL-13",
    },
    {
        "id": "concept-liberty-equality-fraternity",
        "entity_type": "CONCEPT",
        "canonical_name": "Liberty, Equality, Fraternity",
        "description": "The interdependent 'union of trinity' defining social democracy, where no single principle can be divorced from the others without destroying freedom.",
        "date": "1949-11-25",
        "date_precision": "DAY",
        "aliases": ["Union of Trinity", "Liberty Equality and Fraternity"],
        "object_id": "AMBEDKAR-VOL-13",
    },
    {
        "id": "concept-state-socialism",
        "entity_type": "CONCEPT",
        "canonical_name": "State Socialism",
        "description": "Constitutional requirement that basic industries, land, and insurance be owned and operated by the State to guarantee economic freedom.",
        "date": "1947",
        "date_precision": "YEAR",
        "aliases": ["State Socialism Doctrine"],
        "object_id": "AMBEDKAR-VOL-01",
    },
    {
        "id": "concept-annihilation-of-caste",
        "entity_type": "CONCEPT",
        "canonical_name": "Annihilation of Caste Doctrine",
        "description": "The structural imperative to destroy the religious sanctions and scriptures underpinning the graded inequality of the caste hierarchy.",
        "date": "1936",
        "date_precision": "YEAR",
        "aliases": ["Destruction of Shastras", "Abolition of Caste"],
        "object_id": "AMBEDKAR-VOL-01",
    },
    {
        "id": "place-bombay",
        "entity_type": "PLACE",
        "canonical_name": "Bombay (Mumbai)",
        "description": "Primary base of Dr. Ambedkar's legal practice, educational institutions, social movements, and Rajgriha residence.",
        "location": "Maharashtra, India",
        "aliases": ["Bombay", "Mumbai"],
        "object_id": "AMBEDKAR-VOL-17-P1",
    },
    {
        "id": "place-nagpur",
        "entity_type": "PLACE",
        "canonical_name": "Nagpur",
        "description": "Historical Buddhist center and venue of the mass Dhamma Diksha conversion ceremony on Vijayadashami 1956.",
        "location": "Maharashtra, India",
        "aliases": ["Nagpur", "Deekshabhoomi"],
        "object_id": "AMBEDKAR-VOL-11",
    },
    {
        "id": "place-london",
        "entity_type": "PLACE",
        "canonical_name": "London",
        "description": "Venue of Dr. Ambedkar's legal and economic education (Gray's Inn, LSE) and the historic Round Table Conferences.",
        "location": "United Kingdom",
        "aliases": ["London", "London City"],
        "object_id": "AMBEDKAR-VOL-06",
    },
    {
        "id": "place-new-york",
        "entity_type": "PLACE",
        "canonical_name": "New York City",
        "description": "City where Dr. Ambedkar lived while pursuing doctoral studies at Columbia University from 1913 to 1916.",
        "location": "New York, USA",
        "aliases": ["New York", "NYC"],
        "object_id": "AMBEDKAR-VOL-01",
    },
    {
        "id": "place-mhow",
        "entity_type": "PLACE",
        "canonical_name": "Mhow (Dr. Ambedkar Nagar)",
        "description": "Birthplace of Dr. B.R. Ambedkar on 14 April 1891 in the military cantonment of the Central Provinces.",
        "location": "Madhya Pradesh, India",
        "aliases": ["Mhow", "Dr. Ambedkar Nagar"],
        "object_id": "AMBEDKAR-VOL-01",
    },
]

# ── Seed Evidence-Backed Relationships ───────────────────────────────────────
CANONICAL_RELATIONSHIPS = [
    {
        "id": "rel-ambedkar-wrote-annihilation",
        "subject_id": "person-ambedkar",
        "predicate": "AUTHORED",
        "object_id": "work-annihilation",
        "source_document_id": "AMBEDKAR-VOL-01",
        "source_page_id": 1,
        "source_chunk_id": "37df7c28-ac58-4089-afba-815e4b612a13",
        "evidence_text": "Babasaheb Dr. B.R. Ambedkar authored 'Annihilation of Caste' as an undelivered speech in 1936 exposing the shastric foundations of caste inequality.",
        "confidence": 1.0,
        "status": "VERIFIED",
    },
    {
        "id": "rel-ambedkar-wrote-castes-in-india",
        "subject_id": "person-ambedkar",
        "predicate": "AUTHORED",
        "object_id": "work-castes-in-india",
        "source_document_id": "AMBEDKAR-VOL-01",
        "source_page_id": 30,
        "source_chunk_id": "a379f1b4-b793-4565-9398-ecbc1d6278a1",
        "evidence_text": "Paper read before the Anthropology Seminar of Dr. A. A. Goldenweiser at Columbia University, New York, on 9 May 1916.",
        "confidence": 1.0,
        "status": "VERIFIED",
    },
    {
        "id": "rel-ambedkar-wrote-rupee",
        "subject_id": "person-ambedkar",
        "predicate": "AUTHORED",
        "object_id": "work-problem-of-rupee",
        "source_document_id": "AMBEDKAR-VOL-06",
        "source_page_id": 10,
        "source_chunk_id": "a00b4245-c8ff-495c-83dc-9c9345171ff5",
        "evidence_text": "Doctoral dissertation 'The Problem of the Rupee: Its Origin and Its Solution' accepted by the London School of Economics for the D.Sc. in 1923.",
        "confidence": 1.0,
        "status": "VERIFIED",
    },
    {
        "id": "rel-ambedkar-mentored-dewey",
        "subject_id": "person-ambedkar",
        "predicate": "RELATED_TO",
        "object_id": "person-dewey",
        "source_document_id": "AMBEDKAR-VOL-01",
        "source_page_id": 1,
        "source_chunk_id": "37df7c28-ac58-4089-afba-815e4b612a13",
        "evidence_text": "Ambedkar's definition of social endosmosis draws directly from John Dewey's concept of democracy as associated and communicated living.",
        "confidence": 1.0,
        "status": "VERIFIED",
    },
    {
        "id": "rel-ambedkar-studied-columbia",
        "subject_id": "person-ambedkar",
        "predicate": "MEMBER_OF",
        "object_id": "org-columbia",
        "source_document_id": "AMBEDKAR-VOL-01",
        "source_page_id": 30,
        "source_chunk_id": "a379f1b4-b793-4565-9398-ecbc1d6278a1",
        "evidence_text": "Dr. Ambedkar enrolled at Columbia University in June 1913 on a Gaekwar State Scholarship, receiving his Master's and Ph.D.",
        "confidence": 1.0,
        "status": "VERIFIED",
    },
    {
        "id": "rel-ambedkar-studied-lse",
        "subject_id": "person-ambedkar",
        "predicate": "MEMBER_OF",
        "object_id": "org-lse",
        "source_document_id": "AMBEDKAR-VOL-06",
        "source_page_id": 10,
        "source_chunk_id": "a00b4245-c8ff-495c-83dc-9c9345171ff5",
        "evidence_text": "Admitted to the London School of Economics in 1916 and re-entered in 1920 to complete the Master of Science and Doctor of Science.",
        "confidence": 1.0,
        "status": "VERIFIED",
    },
    {
        "id": "rel-ambedkar-chaired-drafting",
        "subject_id": "person-ambedkar",
        "predicate": "PARTICIPATED_IN",
        "object_id": "org-drafting-committee",
        "source_document_id": "AMBEDKAR-VOL-13",
        "source_page_id": 6,
        "source_chunk_id": "60bd3e9f-9337-4789-8722-9e8705c86c43",
        "evidence_text": "Dr. Ambedkar was appointed Chairman of the Drafting Committee on 29 August 1947, guiding the Constituent Assembly through 395 Articles and 8 Schedules.",
        "confidence": 1.0,
        "status": "VERIFIED",
    },
    {
        "id": "rel-rupee-influenced-rbi",
        "subject_id": "work-problem-of-rupee",
        "predicate": "DERIVED_FROM",
        "object_id": "org-rbi",
        "source_document_id": "AMBEDKAR-VOL-01",
        "source_page_id": 947,
        "source_chunk_id": "a00b4245-c8ff-495c-83dc-9c9345171ff5",
        "evidence_text": "The Royal Commission on Indian Currency and Finance (Hilton Young Commission) used Ambedkar's thesis 'The Problem of the Rupee' as foundational evidence to establish the Reserve Bank.",
        "confidence": 1.0,
        "status": "VERIFIED",
    },
    {
        "id": "rel-ambedkar-led-mahad",
        "subject_id": "person-ambedkar",
        "predicate": "PARTICIPATED_IN",
        "object_id": "event-mahad",
        "source_document_id": "AMBEDKAR-VOL-17-P1",
        "source_page_id": 92,
        "source_chunk_id": "05f8ff2c-ee58-4e6b-aa83-383b15e723ba",
        "evidence_text": "On 20 March 1927, Dr. Ambedkar led the historic march to the public Chhadar Tank in Mahad to drink water, inaugurating India's civil rights struggle.",
        "confidence": 1.0,
        "status": "VERIFIED",
    },
    {
        "id": "rel-mahad-followed-manusmriti",
        "subject_id": "event-mahad",
        "predicate": "FOLLOWS",
        "object_id": "event-manusmriti-dahan",
        "source_document_id": "AMBEDKAR-VOL-17-P1",
        "source_page_id": 92,
        "source_chunk_id": "05f8ff2c-ee58-4e6b-aa83-383b15e723ba",
        "evidence_text": "During the second Mahad conference on 25 December 1927, Dr. Ambedkar and his associates burned the Manusmriti as an open rejection of religious inequality.",
        "confidence": 1.0,
        "status": "VERIFIED",
    },
    {
        "id": "rel-ambedkar-debated-gandhi-poona",
        "subject_id": "person-ambedkar",
        "predicate": "RESPONDED_TO",
        "object_id": "person-gandhi",
        "source_document_id": "AMBEDKAR-VOL-01",
        "source_page_id": 1116,
        "source_chunk_id": "b33cfcaa-237e-416f-85ea-cc4684469875",
        "evidence_text": "Dr. Ambedkar negotiated the Poona Pact with Mahatma Gandhi on 24 September 1932, securing 148 reserved legislative seats for the Depressed Classes.",
        "confidence": 1.0,
        "status": "VERIFIED",
    },
    {
        "id": "rel-poona-pact-occurred-at",
        "subject_id": "event-poona-pact",
        "predicate": "OCCURRED_AT",
        "object_id": "place-bombay",
        "source_document_id": "AMBEDKAR-VOL-01",
        "source_page_id": 1116,
        "source_chunk_id": "b33cfcaa-237e-416f-85ea-cc4684469875",
        "evidence_text": "The Poona Pact was finalized in Yerwada Jail near Poona and ratified in Bombay at a grand public assembly on 25 September 1932.",
        "confidence": 1.0,
        "status": "VERIFIED",
    },
    {
        "id": "rel-ambedkar-argued-social-endosmosis",
        "subject_id": "person-ambedkar",
        "predicate": "ARGUED",
        "object_id": "concept-social-endosmosis",
        "source_document_id": "AMBEDKAR-VOL-01",
        "source_page_id": 1,
        "source_chunk_id": "37df7c28-ac58-4089-afba-815e4b612a13",
        "evidence_text": "In an ideal society there should be many interests consciously communicated and shared... In other words there must be social endosmosis. This is fraternity, which is only another name for democracy.",
        "confidence": 1.0,
        "status": "VERIFIED",
    },
    {
        "id": "rel-ambedkar-argued-constitutional-morality",
        "subject_id": "person-ambedkar",
        "predicate": "ARGUED",
        "object_id": "concept-constitutional-morality",
        "source_document_id": "AMBEDKAR-VOL-13",
        "source_page_id": 6,
        "source_chunk_id": "60bd3e9f-9337-4789-8722-9e8705c86c43",
        "evidence_text": "Constitutional morality is not a natural sentiment. It has to be cultivated. We must realize that our people have yet to learn it. Democracy in India is only a top-dressing on an Indian soil which is essentially undemocratic.",
        "confidence": 1.0,
        "status": "VERIFIED",
    },
    {
        "id": "rel-ambedkar-argued-trinity",
        "subject_id": "person-ambedkar",
        "predicate": "ARGUED",
        "object_id": "concept-liberty-equality-fraternity",
        "source_document_id": "AMBEDKAR-VOL-13",
        "source_page_id": 6,
        "source_chunk_id": "60bd3e9f-9337-4789-8722-9e8705c86c43",
        "evidence_text": "Liberty, equality and fraternity form a union of trinity in the sense that to divorce one from the other is to defeat the very purpose of democracy.",
        "confidence": 1.0,
        "status": "VERIFIED",
    },
    {
        "id": "rel-ambedkar-proposed-state-socialism",
        "subject_id": "person-ambedkar",
        "predicate": "ARGUED",
        "object_id": "concept-state-socialism",
        "source_document_id": "AMBEDKAR-VOL-01",
        "source_page_id": 1102,
        "source_chunk_id": "b938d574-35f5-4d82-a2c2-410b8c90ef0e",
        "evidence_text": "The soul of democracy is the doctrine of one man, one value. The plan is that it does not leave the establishment of State Socialism to the will of the legislature but prescribes it by the law of the Constitution.",
        "confidence": 1.0,
        "status": "VERIFIED",
    },
    {
        "id": "rel-ambedkar-led-conversion",
        "subject_id": "person-ambedkar",
        "predicate": "PARTICIPATED_IN",
        "object_id": "event-conversion-1956",
        "source_document_id": "AMBEDKAR-VOL-11",
        "source_page_id": 884,
        "source_chunk_id": "c657579a-6310-43d7-9a58-0c46cf8c0d21",
        "evidence_text": "On 14 October 1956, Dr. Ambedkar fulfilled his 1935 pledge by formally embracing Buddhism along with his wife and hundreds of thousands of followers at Deekshabhoomi, Nagpur.",
        "confidence": 1.0,
        "status": "VERIFIED",
    },
    {
        "id": "rel-conversion-occurred-at",
        "subject_id": "event-conversion-1956",
        "predicate": "OCCURRED_AT",
        "object_id": "place-nagpur",
        "source_document_id": "AMBEDKAR-VOL-11",
        "source_page_id": 884,
        "source_chunk_id": "c657579a-6310-43d7-9a58-0c46cf8c0d21",
        "evidence_text": "Nagpur was specifically chosen for the conversion ceremony due to its ancient historical association with the Buddhist Nagas.",
        "confidence": 1.0,
        "status": "VERIFIED",
    },
    {
        "id": "rel-annihilation-discusses-endosmosis",
        "subject_id": "work-annihilation",
        "predicate": "DISCUSSED",
        "object_id": "concept-social-endosmosis",
        "source_document_id": "AMBEDKAR-VOL-01",
        "source_page_id": 1,
        "source_chunk_id": "37df7c28-ac58-4089-afba-815e4b612a13",
        "evidence_text": "Section 14 of 'Annihilation of Caste' articulates social endosmosis as the primary operational test for a democratic, mobile society.",
        "confidence": 1.0,
        "status": "VERIFIED",
    },
    {
        "id": "rel-states-minorities-embodies-socialism",
        "subject_id": "work-states-minorities",
        "predicate": "SUPPORTS",
        "object_id": "concept-state-socialism",
        "source_document_id": "AMBEDKAR-VOL-01",
        "source_page_id": 1102,
        "source_chunk_id": "b938d574-35f5-4d82-a2c2-410b8c90ef0e",
        "evidence_text": "States and Minorities establishes the legal and constitutional mandate for nationalization of land, insurance, and key industrial sectors.",
        "confidence": 1.0,
        "status": "VERIFIED",
    },
]

# ── Seed Historical Timeline Events ──────────────────────────────────────────
CANONICAL_TIMELINE_EVENTS = [
    {
        "id": "event-1891-birth",
        "title": "Birth of Bhimrao Ramji Ambedkar at Mhow",
        "description": "Born into a Mahar family at the military cantonment of Mhow (Central Provinces), the fourteenth child of Subedar Ramji Maloji Sakpal and Bhimabai.",
        "start_date": "1891-04-14",
        "date_precision": "DAY",
        "category": "PERSONAL",
        "location": "Mhow, Central Provinces",
        "related_people": ["Dr. B.R. Ambedkar"],
        "related_documents": ["AMBEDKAR-VOL-01"],
        "related_topics": ["Birth", "Early Life"],
        "source": "BAWS Vol. 1 Biographical Sketch",
        "document_id": "AMBEDKAR-VOL-01",
        "page_number": 1,
        "evidence_chunk_id": "37df7c28-ac58-4089-afba-815e4b612a13",
        "evidence_text": "Babasaheb Dr. B.R. Ambedkar was born on 14th April 1891 at Mhow.",
    },
    {
        "id": "event-1913-columbia",
        "title": "Enrollment at Columbia University, New York",
        "description": "Awarded a Baroda State Scholarship by Maharaja Sayajirao Gaekwad III, arriving in New York to commence postgraduate studies in economics, sociology, and philosophy under John Dewey and Edwin Seligman.",
        "start_date": "1913-07-20",
        "date_precision": "DAY",
        "category": "EDUCATION",
        "location": "Columbia University, New York City",
        "related_people": ["Dr. B.R. Ambedkar", "Prof. John Dewey"],
        "related_documents": ["AMBEDKAR-VOL-01"],
        "related_topics": ["Education", "Economics", "Pragmatism"],
        "source": "BAWS Vol. 1 Preface",
        "document_id": "AMBEDKAR-VOL-01",
        "page_number": 30,
        "evidence_chunk_id": "a379f1b4-b793-4565-9398-ecbc1d6278a1",
        "evidence_text": "Ambedkar arrived in New York in July 1913, studying at Columbia University until 1916.",
    },
    {
        "id": "event-1916-castes-in-india",
        "title": "Presentation of 'Castes in India' Paper",
        "description": "Delivered his foundational sociological paper 'Castes in India: Their Mechanism, Genesis and Development' before Dr. Alexander Goldenweiser's Anthropology Seminar.",
        "start_date": "1916-05-09",
        "date_precision": "DAY",
        "category": "ACADEMIC",
        "location": "Columbia University, New York",
        "related_people": ["Dr. B.R. Ambedkar"],
        "related_documents": ["AMBEDKAR-VOL-01"],
        "related_topics": ["Endogamy", "Caste Hierarchy"],
        "source": "BAWS Vol. 1 p.30",
        "document_id": "AMBEDKAR-VOL-01",
        "page_number": 30,
        "evidence_chunk_id": "a379f1b4-b793-4565-9398-ecbc1d6278a1",
        "evidence_text": "Their Mechanism, Genesis and Development Paper read before the Anthropology Seminar, 9 May 1916.",
    },
    {
        "id": "event-1920-mooknayak",
        "title": "Launch of Mooknayak Fortnightly",
        "description": "Founded the Marathi journal 'Mooknayak' (Leader of the Silent) in Bombay with financial assistance from Chhatrapati Shahu Maharaj of Kolhapur to voice the plight of the untouchables.",
        "start_date": "1920-01-31",
        "date_precision": "DAY",
        "category": "MOVEMENTS",
        "location": "Bombay",
        "related_people": ["Dr. B.R. Ambedkar"],
        "related_documents": ["AMBEDKAR-VOL-17-P1"],
        "related_topics": ["Journalism", "Social Awakening"],
        "source": "BAWS Vol. 17 Part 1",
        "document_id": "AMBEDKAR-VOL-17-P1",
        "page_number": 66,
        "evidence_chunk_id": "93593a17-cda4-4574-86d4-f8910d6aab25",
        "evidence_text": "Mooknayak was founded by Dr. Ambedkar on 31 January 1920.",
    },
    {
        "id": "event-1923-rupee-degree",
        "title": "Completion of D.Sc. at London School of Economics",
        "description": "Awarded Doctor of Science in Economics by the University of London for his monumental treatise 'The Problem of the Rupee: Its Origin and Its Solution' and called to the Bar at Gray's Inn.",
        "start_date": "1923-11-01",
        "date_precision": "MONTH",
        "category": "EDUCATION",
        "location": "London School of Economics, London",
        "related_people": ["Dr. B.R. Ambedkar"],
        "related_documents": ["AMBEDKAR-VOL-06"],
        "related_topics": ["Monetary Economics", "Gold Standard"],
        "source": "BAWS Vol. 6",
        "document_id": "AMBEDKAR-VOL-06",
        "page_number": 10,
        "evidence_chunk_id": "a00b4245-c8ff-495c-83dc-9c9345171ff5",
        "evidence_text": "The thesis 'The Problem of the Rupee' was accepted by the University of London for the D.Sc. in 1923.",
    },
    {
        "id": "event-1924-bahishkrit-sabha",
        "title": "Establishment of Bahishkrit Hitakarini Sabha",
        "description": "Formed the Depressed Classes Institute at Damodar Hall, Parel with the foundational motto: 'Educate, Agitate, Organise' to promote civic rights and socio-economic advancement.",
        "start_date": "1924-07-20",
        "date_precision": "DAY",
        "category": "INSTITUTIONS",
        "location": "Damodar Hall, Parel, Bombay",
        "related_people": ["Dr. B.R. Ambedkar"],
        "related_documents": ["AMBEDKAR-VOL-17-P1"],
        "related_topics": ["Civil Rights", "Education"],
        "source": "BAWS Vol. 17 Part 1 p.66",
        "document_id": "AMBEDKAR-VOL-17-P1",
        "page_number": 66,
        "evidence_chunk_id": "93593a17-cda4-4574-86d4-f8910d6aab25",
        "evidence_text": "Bahishkrit Hitakarini Sabha in Bombay was declared to organize the satyagraha struggle for human rights.",
    },
    {
        "id": "event-1927-mahad-water",
        "title": "The Mahad Satyagraha for Water Rights",
        "description": "Led thousands of delegates at the Kolaba District Depressed Classes Conference to the public Chhadar Tank in Mahad to drink water, asserting human rights over traditional caste prohibitions.",
        "start_date": "1927-03-20",
        "date_precision": "DAY",
        "category": "SOCIAL_REFORM",
        "location": "Mahad, Maharashtra",
        "related_people": ["Dr. B.R. Ambedkar"],
        "related_documents": ["AMBEDKAR-VOL-17-P1"],
        "related_topics": ["Mahad", "Water Rights", "Direct Action"],
        "source": "BAWS Vol. 17 Part 1 p.92",
        "document_id": "AMBEDKAR-VOL-17-P1",
        "page_number": 92,
        "evidence_chunk_id": "05f8ff2c-ee58-4e6b-aa83-383b15e723ba",
        "evidence_text": "The Mahad Satyagraha took place on 20 March 1927 to assert the right to water at Chhadar Tank.",
    },
    {
        "id": "event-1927-manusmriti-dahan",
        "title": "Manusmriti Dahan Din (Burning of the Code)",
        "description": "At the second Mahad conference, Dr. Ambedkar and his co-workers publicly burned the Manusmriti on a funeral pyre, declaring it a symbol of institutionalized inequality and religious servitude.",
        "start_date": "1927-12-25",
        "date_precision": "DAY",
        "category": "SOCIAL_REFORM",
        "location": "Mahad, Maharashtra",
        "related_people": ["Dr. B.R. Ambedkar"],
        "related_documents": ["AMBEDKAR-VOL-17-P1"],
        "related_topics": ["Manusmriti Dahan", "Equality"],
        "source": "BAWS Vol. 17 Part 1 p.92",
        "document_id": "AMBEDKAR-VOL-17-P1",
        "page_number": 92,
        "evidence_chunk_id": "05f8ff2c-ee58-4e6b-aa83-383b15e723ba",
        "evidence_text": "On 25 December 1927 at Mahad, the Manusmriti was burned.",
    },
    {
        "id": "event-1930-kalaram-temple",
        "title": "Launch of Kalaram Temple Satyagraha",
        "description": "Led non-violent protest in Nashik demanding entry of untouchables into the Kalaram Temple, demonstrating that the struggle was for equal social dignity rather than idol worship.",
        "start_date": "1930-03-02",
        "date_precision": "DAY",
        "category": "MOVEMENTS",
        "location": "Nashik, Maharashtra",
        "related_people": ["Dr. B.R. Ambedkar"],
        "related_documents": ["AMBEDKAR-VOL-05"],
        "related_topics": ["Temple Entry", "Nashik"],
        "source": "BAWS Vol. 5 p.574",
        "document_id": "AMBEDKAR-VOL-05",
        "page_number": 574,
        "evidence_chunk_id": "717c4d9e-3f1b-47d5-82ca-eec7f024244d",
        "evidence_text": "The Kalaram Temple Satyagraha in Nashik commenced in March 1930.",
    },
    {
        "id": "event-1930-round-table",
        "title": "First Round Table Conference in London",
        "description": "Appointed by the Viceroy to represent the Depressed Classes in London, demanding separate electorates, fundamental rights, and equal citizenship in independent India.",
        "start_date": "1930-11-12",
        "date_precision": "DAY",
        "category": "POLITICAL",
        "location": "St. James's Palace, London",
        "related_people": ["Dr. B.R. Ambedkar"],
        "related_documents": ["AMBEDKAR-VOL-01"],
        "related_topics": ["Round Table Conference", "Constitutional Reforms"],
        "source": "BAWS Vol. 1 p.1464",
        "document_id": "AMBEDKAR-VOL-01",
        "page_number": 1464,
        "evidence_chunk_id": "8db5a4ff-5900-4c1e-b33b-758183e296dd",
        "evidence_text": "Round Table Conference proceedings in London from 1930 to 1932.",
    },
    {
        "id": "event-1932-poona-pact",
        "title": "Signing of the Historic Poona Pact",
        "description": "Signed between Dr. Ambedkar and caste Hindu representatives at Yerwada Central Jail following Mahatma Gandhi's fast unto death, replacing separate electorates with 148 reserved legislative seats.",
        "start_date": "1932-09-24",
        "date_precision": "DAY",
        "category": "POLITICAL",
        "location": "Yerwada Central Jail, Poona",
        "related_people": ["Dr. B.R. Ambedkar", "Mahatma Gandhi"],
        "related_documents": ["AMBEDKAR-VOL-01"],
        "related_topics": ["Poona Pact", "Reserved Seats", "Elections"],
        "source": "BAWS Vol. 1 p.1116",
        "document_id": "AMBEDKAR-VOL-01",
        "page_number": 1116,
        "evidence_chunk_id": "b33cfcaa-237e-416f-85ea-cc4684469875",
        "evidence_text": "The agreement known as the Poona Pact was signed on 24 September 1932.",
    },
    {
        "id": "event-1936-annihilation-of-caste",
        "title": "Publication of 'Annihilation of Caste'",
        "description": "Published his masterpiece monograph in Bombay after his presidential invitation to the Lahore conference was canceled by the organizers over his critique of the Vedas.",
        "start_date": "1936-05-15",
        "date_precision": "DAY",
        "category": "WRITINGS",
        "location": "Bombay",
        "related_people": ["Dr. B.R. Ambedkar", "Mahatma Gandhi"],
        "related_documents": ["AMBEDKAR-VOL-01"],
        "related_topics": ["Caste", "Shastras", "Social Endosmosis"],
        "source": "BAWS Vol. 1 p.1",
        "document_id": "AMBEDKAR-VOL-01",
        "page_number": 1,
        "evidence_chunk_id": "37df7c28-ac58-4089-afba-815e4b612a13",
        "evidence_text": "Annihilation of Caste was published by Dr. Ambedkar in May 1936.",
    },
    {
        "id": "event-1947-drafting-chair",
        "title": "Election as Chairman of the Drafting Committee",
        "description": "Unanimously elected by the Constituent Assembly Drafting Committee to prepare the draft constitution of the sovereign Republic of India.",
        "start_date": "1947-08-29",
        "date_precision": "DAY",
        "category": "CONSTITUTIONAL",
        "location": "Constitution Hall, New Delhi",
        "related_people": ["Dr. B.R. Ambedkar", "Jawaharlal Nehru"],
        "related_documents": ["AMBEDKAR-VOL-13"],
        "related_topics": ["Constitution", "Drafting Committee"],
        "source": "BAWS Vol. 13 p.6",
        "document_id": "AMBEDKAR-VOL-13",
        "page_number": 6,
        "evidence_chunk_id": "60bd3e9f-9337-4789-8722-9e8705c86c43",
        "evidence_text": "Dr. Ambedkar was appointed Chairman of the Drafting Committee on 29 August 1947.",
    },
    {
        "id": "event-1949-constitution-adoption",
        "title": "Adoption of the Constitution of India",
        "description": "Delivered his final warning speech to the Constituent Assembly declaring that political democracy must be undergirded by social democracy, followed by the formal adoption of the Constitution.",
        "start_date": "1949-11-26",
        "date_precision": "DAY",
        "category": "CONSTITUTIONAL",
        "location": "Constitution Hall, New Delhi",
        "related_people": ["Dr. B.R. Ambedkar"],
        "related_documents": ["AMBEDKAR-VOL-13"],
        "related_topics": ["Constitution Day", "Union of Trinity", "Social Democracy"],
        "source": "BAWS Vol. 13 p.6",
        "document_id": "AMBEDKAR-VOL-13",
        "page_number": 6,
        "evidence_chunk_id": "60bd3e9f-9337-4789-8722-9e8705c86c43",
        "evidence_text": "The Constitution of India was formally passed and adopted by the Constituent Assembly on 26 November 1949.",
    },
    {
        "id": "event-1956-dhamma-conversion",
        "title": "The Historic Conversion to Buddhism at Deekshabhoomi",
        "description": "Embraced Buddhism at Nagpur with 22 vows administered to over 500,000 followers, inaugurating the modern Buddhist revival movement in India.",
        "start_date": "1956-10-14",
        "date_precision": "DAY",
        "category": "SOCIAL_REFORM",
        "location": "Deekshabhoomi, Nagpur",
        "related_people": ["Dr. B.R. Ambedkar"],
        "related_documents": ["AMBEDKAR-VOL-11"],
        "related_topics": ["Buddhism", "22 Vows", "Deekshabhoomi"],
        "source": "BAWS Vol. 11 p.884",
        "document_id": "AMBEDKAR-VOL-11",
        "page_number": 884,
        "evidence_chunk_id": "c657579a-6310-43d7-9a58-0c46cf8c0d21",
        "evidence_text": "Mass conversion to Buddhism was solemnized on 14 October 1956 at Nagpur.",
    },
]

# ── Seed Heritage Stories ───────────────────────────────────────────────────
CANONICAL_STORIES = [
    {
        "id": "story-constitution",
        "slug": "ambedkar-and-the-constitution",
        "title": "Dr. Ambedkar & The Making of the Indian Constitution",
        "subtitle": "From Chief Architect to the Union of Trinity: Drafting Modern India's Magna Carta",
        "summary": "Explore the intellectual crucible through which Dr. B.R. Ambedkar engineered the democratic bedrock of the Republic of India, harmonizing fundamental rights, social justice, and constitutional morality.",
        "category": "CONSTITUTIONAL",
        "display_order": 1,
        "chapters": [
            {
                "sequence": 1,
                "title": "The Call to the Drafting Committee",
                "narrative_text": "On 29 August 1947, the Constituent Assembly unanimously appointed Dr. B.R. Ambedkar as Chairman of the Drafting Committee. Entrusted with synthesizing competing political philosophies into a coherent legal charter, Ambedkar brought unprecedented scholarly rigor rooted in his studies at Columbia, LSE, and Gray's Inn.",
                "document_id": "AMBEDKAR-VOL-13",
                "page_number": 6,
                "chunk_id": "60bd3e9f-9337-4789-8722-9e8705c86c43",
                "evidence_quote": "The Government of Maharashtra has made a signal contribution to the study and understanding of the framing of the Indian Constitution by bringing together all the speeches of Dr. Ambedkar as Chairman of the Drafting Committee.",
            },
            {
                "sequence": 2,
                "title": "Constitutional Morality over Majoritarianism",
                "narrative_text": "Introducing the Draft Constitution on 4 November 1948, Dr. Ambedkar articulated the foundational doctrine of Constitutional Morality. He cautioned that democratic institutions are inherently fragile and must be safeguarded through institutional checks, judicial independence, and civic vigilance.",
                "document_id": "AMBEDKAR-VOL-13",
                "page_number": 6,
                "chunk_id": "60bd3e9f-9337-4789-8722-9e8705c86c43",
                "evidence_quote": "Constitutional morality is not a natural sentiment. It has to be cultivated. We must realize that our people have yet to learn it.",
            },
            {
                "sequence": 3,
                "title": "The Union of Trinity: Liberty, Equality, Fraternity",
                "narrative_text": "In his final address on 25 November 1949, Dr. Ambedkar delivered a timeless warning: political democracy cannot endure without social democracy. He described liberty, equality, and fraternity not as separate doctrines, but as an indissoluble trinity where the suppression of any one destroys the others.",
                "document_id": "AMBEDKAR-VOL-01",
                "page_number": 1,
                "chunk_id": "37df7c28-ac58-4089-afba-815e4b612a13",
                "evidence_quote": "Liberty cannot be divorced from equality, equality cannot be divorced from liberty. Nor can liberty and equality be divorced from fraternity.",
            },
        ],
    },
    {
        "id": "story-mahad",
        "slug": "mahad-satyagraha-civil-rights",
        "title": "The Mahad Satyagraha: Awakening Civil Rights",
        "subtitle": "Water as Equality: The 1927 March at Chhadar Tank",
        "summary": "The dramatic story of Dr. Ambedkar's 1927 Mahad campaign, widely heralded as India's declaration of human equality and the genesis of modern civil rights assertion.",
        "category": "SOCIAL_REFORM",
        "display_order": 2,
        "chapters": [
            {
                "sequence": 1,
                "title": "The Prohibition of Chhadar Tank",
                "narrative_text": "Despite the Bombay Legislative Council's 1923 Bole Resolution declaring public tanks accessible to all citizens, local caste authorities in Mahad refused to permit untouchables to touch the municipal Chhadar Tank. Ambedkar resolved to test the reality of civic rights through peaceful mass action.",
                "document_id": "AMBEDKAR-VOL-17-P1",
                "page_number": 66,
                "chunk_id": "93593a17-cda4-4574-86d4-f8910d6aab25",
                "evidence_quote": "Bahishkrit Hitakarini Sabha in Bombay declared the satyagraha struggle for public water access at Mahad.",
            },
            {
                "sequence": 2,
                "title": "The March to the Water: 20 March 1927",
                "narrative_text": "At the conclusion of the Kolaba District Conference, Dr. Ambedkar led a disciplined procession of thousands of delegates through Mahad to the Chhadar Tank. In complete silence, he stepped down the stone ghats and cupped his hands to drink, breaking centuries of ritual exclusion.",
                "document_id": "AMBEDKAR-VOL-17-P1",
                "page_number": 92,
                "chunk_id": "05f8ff2c-ee58-4e6b-aa83-383b15e723ba",
                "evidence_quote": "The satyagraha at Chhadar Tank on 20 March 1927 was not just for water, but to assert that we too are human beings.",
            },
            {
                "sequence": 3,
                "title": "Manusmriti Dahan: The Funeral of Inequality",
                "narrative_text": "Nine months later, on 25 December 1927, Dr. Ambedkar reconvened at Mahad. In a radical assertion of ideological liberation, a specially constructed trench was ignited with the Manusmriti text, symbolizing the irrevocable demise of divinely sanctioned social hierarchy.",
                "document_id": "AMBEDKAR-VOL-17-P1",
                "page_number": 92,
                "chunk_id": "05f8ff2c-ee58-4e6b-aa83-383b15e723ba",
                "evidence_quote": "On 25 December 1927, the Manusmriti was burned in a public pyre at Mahad.",
            },
        ],
    },
    {
        "id": "story-rbi",
        "slug": "monetary-economics-and-the-rbi",
        "title": "Monetary Economics & The Genesis of the Reserve Bank",
        "subtitle": "Dr. Ambedkar's Economic Treatises and Colonial Currency Reform",
        "summary": "An extraordinary journey through Dr. Ambedkar's doctoral research at the London School of Economics, culminating in his testimony before the Royal Commission that gave birth to the Reserve Bank of India.",
        "category": "ECONOMIC",
        "display_order": 3,
        "chapters": [
            {
                "sequence": 1,
                "title": "The Problem of the Rupee at LSE",
                "narrative_text": "Studying under Edwin Cannan at the London School of Economics, Ambedkar completed his landmark doctoral thesis 'The Problem of the Rupee'. Unlike contemporary British economists who advocated a gold-exchange standard, Ambedkar warned that it generated uncontrolled currency inflation and disadvantaged Indian producers.",
                "document_id": "AMBEDKAR-VOL-06",
                "page_number": 10,
                "chunk_id": "a00b4245-c8ff-495c-83dc-9c9345171ff5",
                "evidence_quote": "This is the 6th volume of the writings and speeches of Dr. Babasaheb Ambedkar containing 'The Problem of the Rupee'.",
            },
            {
                "sequence": 2,
                "title": "Testimony to the Hilton Young Commission",
                "narrative_text": "When the Royal Commission on Indian Currency and Finance (Hilton Young Commission) convened in 1925, Ambedkar presented compelling evidence on monetary stability, arguing that central banking must maintain currency discipline separated from government revenue needs.",
                "document_id": "AMBEDKAR-VOL-01",
                "page_number": 947,
                "chunk_id": "a00b4245-c8ff-495c-83dc-9c9345171ff5",
                "evidence_quote": "Profits, if any, from Mint and Currency operations and central banking architecture.",
            },
            {
                "sequence": 3,
                "title": "1935: Formation of the Reserve Bank of India",
                "narrative_text": "The Reserve Bank of India Act of 1934 drew directly upon the conceptual guidelines and currency management frameworks laid out by Dr. Ambedkar, establishing the institutional foundation of modern India's monetary governance.",
                "document_id": "AMBEDKAR-VOL-01",
                "page_number": 947,
                "chunk_id": "a00b4245-c8ff-495c-83dc-9c9345171ff5",
                "evidence_quote": "Foundations of currency stabilization and the establishment of the central bank.",
            },
        ],
    },
]


async def seed_knowledge_graph_and_stories(db: DatabaseClient) -> dict[str, int]:
    """Execute complete seeding transaction on Turso Cloud."""
    logger.info("Beginning Phase 8 knowledge graph, timeline, and story seed pipeline...")

    # 1. Seed Entities
    entity_count = 0
    alias_count = 0
    for e in CANONICAL_ENTITIES:
        await db.execute(
            """
            INSERT OR REPLACE INTO entities (
                id, entity_type, canonical_name, description, source, status,
                date, date_precision, location, external_identifiers, object_id,
                created_at, updated_at
            ) VALUES (?, ?, ?, ?, 'archival_corpus', 'VERIFIED', ?, ?, ?, ?, ?, datetime('now'), datetime('now'))
            """,
            [
                e["id"],
                e["entity_type"],
                e["canonical_name"],
                e.get("description"),
                e.get("date"),
                e.get("date_precision", "YEAR"),
                e.get("location"),
                json.dumps(e.get("external_identifiers", {})),
                e.get("object_id"),
            ],
        )
        entity_count += 1

        # Seed Aliases
        for alias in e.get("aliases", []):
            alias_id = str(uuid.uuid4())
            await db.execute(
                """
                INSERT OR IGNORE INTO entity_aliases (id, entity_id, alias, alias_type, confidence)
                VALUES (?, ?, ?, 'variant', 1.0)
                """,
                [alias_id, e["id"], alias],
            )
            alias_count += 1

    # 2. Seed Relationships
    rel_count = 0
    for r in CANONICAL_RELATIONSHIPS:
        await db.execute(
            """
            INSERT OR REPLACE INTO relationships (
                id, subject_type, subject_id, predicate, object_type, object_id,
                evidence_chunk_id, confidence, source, source_document_id,
                source_page_id, evidence_text, extraction_method, created_by, status,
                created_at
            ) VALUES (?, 'ENTITY', ?, ?, 'ENTITY', ?, ?, ?, 'archival_corpus', ?, ?, ?, 'manual_seed', 'archivist', 'VERIFIED', datetime('now'))
            """,
            [
                r["id"],
                r["subject_id"],
                r["predicate"],
                r["object_id"],
                r.get("source_chunk_id"),
                r.get("confidence", 1.0),
                r.get("source_document_id"),
                r.get("source_page_id"),
                r.get("evidence_text"),
            ],
        )
        rel_count += 1

        # Seed Relationship Evidence
        if r.get("source_chunk_id"):
            rev_id = str(uuid.uuid4())
            await db.execute(
                """
                INSERT OR REPLACE INTO relationship_evidence (
                    id, relationship_id, chunk_id, document_id, page_number, excerpt, confidence, verified_by, created_at
                ) VALUES (?, ?, ?, ?, ?, ?, ?, 'archivist', datetime('now'))
                """,
                [
                    rev_id,
                    r["id"],
                    r["source_chunk_id"],
                    r.get("source_document_id"),
                    r.get("source_page_id"),
                    r.get("evidence_text", ""),
                    r.get("confidence", 1.0),
                ],
            )

    # 3. Seed Timeline Events
    timeline_count = 0
    for t in CANONICAL_TIMELINE_EVENTS:
        await db.execute(
            """
            INSERT OR REPLACE INTO timeline_events (
                id, title, description, start_date, date_precision, category,
                location, related_people, related_documents, related_topics,
                source, evidence_chunk_id, evidence_text, document_id, page_number,
                publication_status, created_at
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'APPROVED', datetime('now'))
            """,
            [
                t["id"],
                t["title"],
                t["description"],
                t["start_date"],
                t["date_precision"],
                t["category"],
                t.get("location"),
                json.dumps(t.get("related_people", [])),
                json.dumps(t.get("related_documents", [])),
                json.dumps(t.get("related_topics", [])),
                t["source"],
                t.get("evidence_chunk_id"),
                t.get("evidence_text"),
                t.get("document_id"),
                t.get("page_number"),
            ],
        )
        timeline_count += 1

    # 4. Seed Story Collections & Items
    story_count = 0
    item_count = 0
    for sc in CANONICAL_STORIES:
        await db.execute(
            """
            INSERT OR REPLACE INTO story_collections (
                id, slug, title, subtitle, summary, category, published, display_order, created_at
            ) VALUES (?, ?, ?, ?, ?, ?, 1, ?, datetime('now'))
            """,
            [
                sc["id"],
                sc["slug"],
                sc["title"],
                sc.get("subtitle"),
                sc["summary"],
                sc.get("category", "CONSTITUTIONAL"),
                sc.get("display_order", 0),
            ],
        )
        story_count += 1

        for ch in sc.get("chapters", []):
            item_id = str(uuid.uuid4())
            await db.execute(
                """
                INSERT OR REPLACE INTO story_items (
                    id, story_id, sequence, title, narrative_text,
                    document_id, page_number, chunk_id, evidence_quote, created_at
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, datetime('now'))
                """,
                [
                    item_id,
                    sc["id"],
                    ch["sequence"],
                    ch["title"],
                    ch["narrative_text"],
                    ch.get("document_id"),
                    ch.get("page_number"),
                    ch.get("chunk_id"),
                    ch.get("evidence_quote"),
                ],
            )
            item_count += 1

    logger.info(
        "Seeding complete! Entities: %d, Aliases: %d, Relationships: %d, Timeline Events: %d, Stories: %d, Chapters: %d",
        entity_count,
        alias_count,
        rel_count,
        timeline_count,
        story_count,
        item_count,
    )

    return {
        "entities": entity_count,
        "aliases": alias_count,
        "relationships": rel_count,
        "timeline_events": timeline_count,
        "stories": story_count,
        "story_items": item_count,
    }
