import Link from "next/link";
import { Shield, BookMarked, Globe2, FileText } from "lucide-react";

export default function Footer() {
  return (
    <footer className="border-t border-slate-800/80 bg-slate-950 text-slate-400 text-xs py-10 mt-auto">
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div className="grid grid-cols-1 md:grid-cols-4 gap-8 mb-8">
          {/* Col 1 */}
          <div className="space-y-3">
            <div className="flex items-center gap-2">
              <div className="h-6 w-6 rounded bg-amber-500/20 text-amber-400 flex items-center justify-center font-serif text-xs font-bold border border-amber-500/40">
                BA
              </div>
              <span className="font-semibold text-slate-200">Ambedkar Heritage</span>
            </div>
            <p className="text-slate-400 leading-relaxed">
              Institutional digital preservation archive and intelligence platform dedicated to the
              scholarly works, speeches, and legal draftings of Dr. Bhimrao Ramji Ambedkar.
            </p>
          </div>

          {/* Col 2 */}
          <div>
            <h4 className="font-semibold text-slate-200 uppercase tracking-wider text-[11px] mb-3">
              Corpus & Standards
            </h4>
            <ul className="space-y-2">
              <li className="flex items-center gap-1.5">
                <FileText className="h-3.5 w-3.5 text-amber-400" />
                <span>BAWS Volumes 1–22</span>
              </li>
              <li className="flex items-center gap-1.5">
                <Shield className="h-3.5 w-3.5 text-amber-400" />
                <span>PREMIS 3.0 Preservation Fixity</span>
              </li>
              <li className="flex items-center gap-1.5">
                <BookMarked className="h-3.5 w-3.5 text-amber-400" />
                <span>OAIS Compliant DIP Pipeline</span>
              </li>
              <li className="flex items-center gap-1.5">
                <Globe2 className="h-3.5 w-3.5 text-amber-400" />
                <span>22 Indic Languages Support</span>
              </li>
            </ul>
          </div>

          {/* Col 3 */}
          <div>
            <h4 className="font-semibold text-slate-200 uppercase tracking-wider text-[11px] mb-3">
              Navigation
            </h4>
            <ul className="space-y-1.5">
              <li>
                <Link href="/documents" className="hover:text-amber-300 transition-colors">
                  Archival Objects Catalog
                </Link>
              </li>
              <li>
                <Link href="/search" className="hover:text-amber-300 transition-colors">
                  Hybrid Search Engine
                </Link>
              </li>
              <li>
                <Link href="/timeline" className="hover:text-amber-300 transition-colors">
                  Historical Chronology (1891–1956)
                </Link>
              </li>
              <li>
                <Link href="/assistant" className="hover:text-amber-300 transition-colors">
                  Grounded Research Assistant
                </Link>
              </li>
              <li>
                <Link href="/preservation" className="hover:text-amber-300 transition-colors">
                  Digital Preservation & Fixity
                </Link>
              </li>
            </ul>
          </div>

          {/* Col 4 */}
          <div>
            <h4 className="font-semibold text-slate-200 uppercase tracking-wider text-[11px] mb-3">
              Archival Integrity
            </h4>
            <div className="p-3 rounded-lg bg-slate-900/60 border border-slate-800 text-[11px] text-slate-300 leading-relaxed">
              <span className="text-amber-400 font-semibold block mb-1">Zero-Hallucination Policy</span>
              Every statement generated by the AI research assistant must strictly cite verified
              page-level archival documents. Uncited statements are disallowed.
            </div>
          </div>
        </div>

        <div className="pt-6 border-t border-slate-900 flex flex-col sm:flex-row items-center justify-between gap-4 text-[11px] text-slate-500">
          <div>
            © {new Date().getFullYear()} Dr. B.R. Ambedkar Heritage Intelligence Archive. Scholarly
            Research & Educational Public Good.
          </div>
          <div className="flex gap-4">
            <span>Turso libSQL</span>
            <span>•</span>
            <span>FastAPI 0.141</span>
            <span>•</span>
            <span>Next.js 15</span>
          </div>
        </div>
      </div>
    </footer>
  );
}
